### PR TITLE
[Segmented] Improvements to EqualPanel

### LINKED ISSUE #425: Segmented Control crash if StackPanel Orientation value is Horizontal
### Describe the bug

If `StackPanel` Orientation value is set to Vertical it works, but if is set to Horizontal the app crashes:

**Xaml**

```xaml
<Window
    x:Class="LabsTests.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:LabsTests"
    xmlns:labs="using:CommunityToolkit.Labs.WinUI"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <StackPanel Orientation="Vertical"> <!--If Orientation value is Horizontal, the app crashes-->
        <labs:Segmented SelectedIndex="0"                        
                        SelectionMode="Single">
            <labs:SegmentedItem Content="Item 1">
                <labs:SegmentedItem.Icon>
                    <FontIcon Glyph="&#xEA3A;" />
                </labs:SegmentedItem.Icon>
            </labs:SegmentedItem>
            <labs:SegmentedItem Content="Item 2">
                <labs:SegmentedItem.Icon>
                    <FontIcon Glyph="&#xEA3A;" />
                </labs:SegmentedItem.Icon>
            </labs:SegmentedItem>
            <labs:SegmentedItem Content="Item 3 with a long label">
                <labs:SegmentedItem.Icon>
                    <FontIcon Glyph="&#xEA3A;" />
                </labs:SegmentedItem.Icon>
            </labs:SegmentedItem>
            <labs:SegmentedItem Content="Item 4">
                <labs:SegmentedItem.Icon>
                    <FontIcon Glyph="&#xEA3A;" />
                </labs:SegmentedItem.Icon>
            </labs:SegmentedItem>
        </labs:Segmented>
    </StackPanel>
</Window>
```

**NuGet references**

```csproj
<PackageReference Include="CommunityToolkit.Labs.WinUI.SegmentedControl" Version="0.0.2" />
<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.2.230118.102" />
<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.1" />
```

### Steps to reproduce

```text
1. Create a new WinUI Desktop project.
3. Copy the xml above and use the NuGet references.
4. Set `StackPanel` Orientation value to Horizontal in the example above.
5. Run the app.
```

### Expected behavior

Segmented Control should not crash if StackPanel Orientation is set to Horizontal.

### Screenshots

_No response_

### Code Platform

- [ ] UWP
- [X] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### Other Windows Build number

Windows 10 22H2 Build 19045

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Other (specify)

### Other SDK version

_No response_

### Visual Studio Version

2022

### Visual Studio Build Number

_No response_

### Device form factor

Desktop

### Additional context

_No response_

### Help us help you

No, I'm unable to contribute a solution.

### PR DESCRIPTION
**Pull request by niels9001**
Fixes #425

We didn't handle a potential Infinite width on the `AvailableSize`.. (which happen in edge cases where this control would be in e.g. a `Grid.Column` set to `Auto`. This change makes sure it has a proper fallback. Resolves: #425

Here's an example where the page is rendered in a `Grid.Column` with a `Width` that was set to `Auto`:

SegmentedPanel

### CODE REVIEW

File: components/SegmentedControl/src/EqualPanel.cs [hunk 1]
```diff
@@ -34,21 +34,33 @@ protected override Size MeasureOverride(Size availableSize)
...
         maxItemHeight = 0;
+        int UncollapsedChildrenCount = Children.Where(x => x.Visibility != Visibility.Collapsed).Count();
 
-        if (Children.Count > 0)
+        if (UncollapsedChildrenCount > 0)
         {
-            SetMaxDimensions(Children, availableSize);
+            foreach (var child in Children)
+            {
+                if (child.Visibility != Visibility.Collapsed)
```
Comment (michael-hawker) [inline components/SegmentedControl/src/EqualPanel.cs:43]: We're checking visibility on everything twice here, you can just grab the collection (remove the `.Count()`) of the uncollapsed children. Then in the if add the `.Count()` so that you can just iterate over the collection of uncollapsed children in your foreach loop here and remove the inner `if` visibility check.

File: components/SegmentedControl/src/EqualPanel.cs
Comment (michael-hawker) [inline components/SegmentedControl/src/EqualPanel.cs:1]: Didn't notice before but `maxItemWidth/Height` should start with `_` as fields.

File: components/SegmentedControl/src/EqualPanel.cs [hunk 2]
```diff
@@ -58,32 +70,24 @@ protected override Size MeasureOverride(Size availableSize)
...
-            double desiredHeight = item.DesiredSize.Height;
-            if (desiredHeight > maxItemHeight)
-            {
-                maxItemHeight = desiredHeight;
-            }
+        // Check if there's more width available - if so, recalculate (e.g. whenever Grid.Column is set to Auto)
+        if (finalSize.Width > newWidth)
+        {
+            MeasureOverride(finalSize);
         }
```
Comment (michael-hawker) [inline components/SegmentedControl/src/EqualPanel.cs:88]: We can calculate the `newWidth` based on the Count alone (well the uncollapsed count, we could cache that number or this result in the measure step).

As if we're going to re-measure everything if we have more space, then we should want to do that before we tell everyone what their final size is with `child.Arrange`, no?

**Review by michael-hawker — CHANGES_REQUESTED** [review]
Couple of questions

**Comment by niels9001** [comment]
@michael-hawker Great feedback, I think I addressed your comments.. let me know if I'm missing anything (testing shows expected results 😊)

**Review by Arlodotexe — APPROVED** [review]
Looks good!
